{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "java-k8s-operator.serviceAccountName" . }}
  labels:
{{ include "java-k8s-operator.labels" . | indent 4 }}
{{- end -}}
